name: Build test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build test
    steps:
    - uses: actions/checkout@v4
    - name: Build SyncTv
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        release: 13.2
        prepare: 
          wget https://golang.org/dl/go1.22.freebsd-amd64.tar.gz
          tar -C /usr/local -xzf go1.22.freebsd-amd64.tar.gz
          go version
          
    
